export const users = [
  {
    index: 1,
    name: "yooseung",
    type: "Manager",
    account: 111111,
    spent: 200000,
    events: ["a"],
  },
  {
    index: 2,
    name: "sungjun",
    type: "Depositors",
    account: 111112,
    spent: -100000,
    events: ["b"],
  },
  {
    index: 3,
    name: "jangwon",
    type: "Depositors",
    account: 111113,
    spent: -300000,
    events: ["c"],
  },
  {
    index: 4,
    name: "haeun",
    type: "Recipients",
    account: 111114,
    spent: 100000,
    events: ["c"],
  },
  {
    index: 5,
    name: "prof.Hwang",
    type: "Recipients",
    account: 111115,
    spent: 100000,
    events: ["a"],
  },
  {
    index: 6,
    name: "heejeong",
    type: "Recipients",
    account: 3333180421,
    spent: 150000,
    events: ["Taxi", "SRT", "Beer", "Soju"],
  },
  {
    index: 7,
    name: "doyoon",
    type: "Depositors",
    account: 1240232432,
    spent: -2143423,
    events: ["date", "nba", "study", "starbucks", "eungae"],
  },
  {
    index: 8,
    name: "seyeon",
    type: "Depositors",
    account: 3333181769445,
    spent: -1000000,
    events: ["crossfit", "eat", "dummy", "minions", "abc", "jeongsangsu"],
  },
  {
    index: 9,
    name: "gyojoon",
    type: "Recipients",
    account: 14098390290481,
    spent: 1000000,
    events: ["date", "lotteworld", "seyeon", "gktpdus", "toefl", "busan"],
  },
  {
    index: 10,
    name: "d'Aurial",
    type: "Depositors",
    account: 2900431421,
    spent: -3419025801293,
    events: ["computer_programming", "digital_design"],
  },
];

export var eventList = [
  {
    index: 1,
    place: "newEvent",
    name: "me",
    price: "101010",
    date: "2022/02/28",
    participants: ["sungjun", "haeun", "jangwon", "yooseung"],
  },
  {
    index: 2,
    place: "place",
    name: "name",
    price: "price",
    date: "date",
    participants: [
      "sungjun",
      "haeun",
      "jangwon",
      "yooseung",
      "doyoon",
      "heejeong",
    ],
  },
];
